tickets = [
    # === HARDWARE ===
    ("Laptop won't turn on after charging overnight", "Hardware"),
    ("My laptop screen is flickering with horizontal lines", "Hardware"),
    ("Keyboard keys are sticking and unresponsive", "Hardware"),
    ("Monitor displays no signal when connected", "Hardware"),
    ("Mouse cursor jumping around erratically", "Hardware"),
    ("Laptop battery drains in less than an hour", "Hardware"),
    ("Docking station not recognizing external monitors", "Hardware"),
    ("Printer keeps jamming on floor 3", "Hardware"),
    ("Headset microphone not working in calls", "Hardware"),
    ("USB ports stopped working on my workstation", "Hardware"),
    ("New laptop request for incoming employee", "Hardware"),
    ("Laptop fan is making loud grinding noise", "Hardware"),
    ("Cracked laptop screen needs replacement", "Hardware"),
    ("External hard drive not detected by computer", "Hardware"),
    ("Desktop computer randomly shuts down", "Hardware"),
    ("Need a second monitor for my desk", "Hardware"),
    ("Webcam shows black screen during meetings", "Hardware"),
    ("Power supply unit making buzzing sound", "Hardware"),
    ("Laptop touchpad not responding to clicks", "Hardware"),
    ("Scanner not feeding documents properly", "Hardware"),
    ("RAM upgrade needed for development workstation", "Hardware"),
    ("Projector in conference room B not working", "Hardware"),
    ("Desktop overheating and thermal throttling", "Hardware"),
    ("Laptop hinge is broken and screen wobbles", "Hardware"),
    ("Ethernet port on docking station broken", "Hardware"),
    ("Keyboard backlight stopped working", "Hardware"),
    ("Laptop charger cable is fraying and sparking", "Hardware"),
    ("Need replacement mouse, scroll wheel broken", "Hardware"),
    ("Hard drive making clicking sounds", "Hardware"),
    ("Monitor brightness stuck at maximum", "Hardware"),
    ("Bluetooth adapter not found on desktop", "Hardware"),
    ("Printer printing blank pages", "Hardware"),
    ("Laptop running extremely hot to touch", "Hardware"),
    ("Workstation GPU causing display artifacts", "Hardware"),
    ("Phone headset has static and crackling", "Hardware"),
    ("Display cable loose connection to monitor", "Hardware"),
    ("SSD failing with read errors", "Hardware"),
    ("Laptop lid sensor not detecting close", "Hardware"),
    ("Office printer needs toner replacement", "Hardware"),
    ("Computer won't POST, no beep codes", "Hardware"),
    ("Fingerprint reader not recognizing prints", "Hardware"),
    ("Desk phone not ringing for incoming calls", "Hardware"),
    ("Monitor stand broke, screen fell over", "Hardware"),
    ("Laptop speakers have no sound output", "Hardware"),
    ("Network card hardware failure on desktop", "Hardware"),
    ("HDMI port on laptop not outputting video", "Hardware"),
    ("Keyboard spilled coffee, keys not working", "Hardware"),
    ("Server rack disk drive needs replacement", "Hardware"),
    ("Barcode scanner not reading labels", "Hardware"),
    ("Laptop track point drifting on its own", "Hardware"),

    # === SOFTWARE ===
    ("Outlook keeps crashing when opening attachments", "Software"),
    ("Can't install the latest Windows update", "Software"),
    ("Adobe Creative Cloud license expired", "Software"),
    ("Excel freezes when opening large spreadsheets", "Software"),
    ("Microsoft Teams not launching after update", "Software"),
    ("Need access to Jira for new project", "Software"),
    ("SAP application throwing error code 500", "Software"),
    ("Antivirus blocking internal application", "Software"),
    ("Chrome browser crashes every few minutes", "Software"),
    ("Need Microsoft Project license for my team", "Software"),
    ("Operating system blue screen of death BSOD", "Software"),
    ("Zoom app audio not working in meetings", "Software"),
    ("Python IDE not recognizing virtual environment", "Software"),
    ("Database client can't connect to SQL Server", "Software"),
    ("OneDrive sync stuck and not uploading files", "Software"),
    ("Software update broke existing functionality", "Software"),
    ("PDF editor not saving annotated documents", "Software"),
    ("Visual Studio Code extensions failing to load", "Software"),
    ("Email client not syncing new messages", "Software"),
    ("Java application out of memory error", "Software"),
    ("Slack notifications not appearing on desktop", "Software"),
    ("SharePoint site returning 403 forbidden error", "Software"),
    ("AutoCAD crashing during rendering process", "Software"),
    ("Need to install Docker on my workstation", "Software"),
    ("PowerPoint corrupted file can't be opened", "Software"),
    ("Windows activation expired on my machine", "Software"),
    ("Application hangs at login screen", "Software"),
    ("Need VPN client software installed", "Software"),
    ("Git client showing SSL certificate error", "Software"),
    ("ERP system showing incorrect data entries", "Software"),
    ("Can't open ZIP files after update", "Software"),
    ("Software firewall blocking application traffic", "Software"),
    ("Need upgrade from Office 2019 to Office 365", "Software"),
    ("Password manager extension disappeared from browser", "Software"),
    ("Video editing software rendering very slowly", "Software"),
    ("CRM application timeout errors during peak hours", "Software"),
    ("Excel macros disabled by security policy", "Software"),
    ("App crashes when trying to export reports", "Software"),
    ("Calendar not syncing between phone and desktop", "Software"),
    ("Development environment build errors after update", "Software"),
    ("Backup software failed overnight job", "Software"),
    ("Cannot uninstall old version of application", "Software"),
    ("Browser auto-fill not working on internal sites", "Software"),
    ("Software license server unreachable", "Software"),
    ("Print driver not compatible with new OS version", "Software"),
    ("Two-factor authentication app not generating codes", "Software"),
    ("File association broken for PDF documents", "Software"),
    ("Application asking for admin rights to run", "Software"),
    ("Spell check not working in Word documents", "Software"),
    ("System restore point creation failing", "Software"),

    # === NETWORKING ===
    ("Can't connect to the VPN from home", "Networking"),
    ("WiFi keeps disconnecting every few minutes", "Networking"),
    ("Internet speed extremely slow on floor 2", "Networking"),
    ("Can't access internal company website", "Networking"),
    ("DNS resolution failing for internal domains", "Networking"),
    ("VPN connection drops during video calls", "Networking"),
    ("Network drive not accessible from my computer", "Networking"),
    ("WiFi not showing company SSID in available networks", "Networking"),
    ("Intermittent packet loss causing call drops", "Networking"),
    ("Can't access shared folder on network drive", "Networking"),
    ("Firewall blocking access to external service", "Networking"),
    ("Proxy server refusing connections", "Networking"),
    ("Network printer not discoverable on the network", "Networking"),
    ("Static IP address conflict with another device", "Networking"),
    ("VPN tunnel keeps timing out", "Networking"),
    ("Wireless access point on floor 4 is down", "Networking"),
    ("Can't reach remote desktop server", "Networking"),
    ("DHCP not assigning IP addresses", "Networking"),
    ("Website loading very slowly from office network", "Networking"),
    ("FTP server connection refused", "Networking"),
    ("SSL certificate error when accessing intranet", "Networking"),
    ("Guest WiFi not working in conference rooms", "Networking"),
    ("Network switch port flapping on rack 3", "Networking"),
    ("Latency spikes during peak office hours", "Networking"),
    ("Can't connect to database server from application", "Networking"),
    ("VoIP phones dropping calls intermittently", "Networking"),
    ("Site to site VPN tunnel is down", "Networking"),
    ("Bandwidth throttling affecting video streaming", "Networking"),
    ("MAC address filtering blocking new device", "Networking"),
    ("DNS changes not propagating correctly", "Networking"),
    ("Network segmentation preventing access to resources", "Networking"),
    ("Wireless controller firmware needs updating", "Networking"),
    ("Remote office can't connect to headquarters", "Networking"),
    ("Network monitoring showing high utilization", "Networking"),
    ("Port forwarding not working for internal service", "Networking"),
    ("VLAN misconfiguration causing connectivity issues", "Networking"),
    ("Email server unreachable from external networks", "Networking"),
    ("Cloud service API endpoints timing out", "Networking"),
    ("Load balancer not distributing traffic evenly", "Networking"),
    ("Traceroute showing excessive hops to server", "Networking"),
    ("Can't connect to file server after office move", "Networking"),
    ("Corporate WiFi certificate authentication failing", "Networking"),
    ("Internet outage affecting entire building", "Networking"),
    ("Slow download speeds from internal repositories", "Networking"),
    ("SSH connection to server being refused", "Networking"),
    ("Network access control blocking my laptop", "Networking"),
    ("Video conference quality poor due to bandwidth", "Networking"),
    ("NTP time sync issues across servers", "Networking"),
    ("BGP route changes causing intermittent outages", "Networking"),
    ("Multicast traffic flooding the network", "Networking"),
]
