spring.application.name=service-ticketsense

spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.ldap.urls=${LDAP_URLS}
spring.ldap.base=${LDAP_BASE}
spring.ldap.username=${LDAP_USERNAME}
spring.ldap.password=${LDAP_PASSWORD}

nlp.service.url=${NLP_SERVICE_URL:http://localhost:8000}

ollama.service.url=${OLLAMA_SERVICE_URL:http://localhost:11434}

uploads.dir=${UPLOADS_DIR:/uploads}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB